src/components/PatientLine.tsx, src/pages/PatientsPage.tsx
- fix the double card
- improve spacing
- chance mouse pointer for clickable card
- remove unecessary Row
=> :lipstick: Patient page and line fixes

src/App.tsx, src/pages/PrescriptionsPage.tsx
Also link to the prescription picture
=> :sparkles: Reinstate prescription link

src/components/Header.tsx, src/components/PrivateRoute.tsx, src/context/token.tsx, src/utils/hooks.ts
Make the `useIsLoggedIn()` a 3 state boolean to distinguish between
when the application is still loading vs the user is not logged in.
=> :bug: Don't redirect until application is loaded

src/components/Header.tsx, src/context/error.test.ts, src/context/error.tsx, src/pages/PrescriptionsPage.tsx
Don't report duplicated errors to the UI
=> :children_crossing: Show the error once fix loop

package.json, src/components/Login.tsx, src/components/Register.tsx, src/pages/PatientsPage.tsx, yarn.lock
Adjust to new compiler type safety
=> :arrow_up: yarn upgrade

src/App.tsx, src/pages/PrescriptionPage.tsx, src/pages/PrescriptionsPage.tsx, src/services/api.ts, src/types/index.ts
First iteration for prescription edit.
Note that the patient ID edit is currently disabled, but may later be
a drop down with a patient list.
The photo upload is also disabled as it will be handled via #77
Cllick on the eye icon of the prescription list to see it.
https://mynotif-git-feature-ticket12prescriptionedit-issa-diallo.vercel.app/prescriptions
=> :sparkles: Prescription edit, fixes #12

src/components/ModalDelete.tsx, src/components/PatientForm.tsx
A confirmation delete popup which is going to be visible when the user wants to delete a todo.
- I created a Modal component that takes a state as parameter
> https://github.com/issa-diallo/mynotif_frontend/issues/109
=> :wrench: Refactor button delete fix #109

src/components/PrescriptionForm.tsx, src/pages/PrescriptionPage.tsx, src/services/api.ts, src/types/index.ts
Very basic but working implementation.
We can work on UX in follow up changes.
=> :sparkles: Prescription upload, fix #77

src/components/Header.tsx
=> :bug: Fix render loop, fix #120

src/components/PatientForm.tsx
Add a condition for delete the button
=> :wrench: Delete the button delete fix #127

src/components/PatientForm.tsx
I delete the list of prescriptions associated with the patient
in the patient's detail view we will add the possibility to see the prescriptions
=> :wrench: Delete prescriptions fix #128

src/components/PrescriptionTr.tsx
=> :wrench: Replace a link by icon eye fix #136

src/App.test.tsx
=> :white_check_mark: Fix broken test

src/pages/PatientDetail.tsx, src/pages/PatientsPage.tsx
- I've made some adjustments for patients
=> :wrench: Refactor section patient

src/components/Header.tsx
The menu is directly available and logout is now in profile
=> :recycle: Move navbar to the bottom

src/App.css, src/App.tsx, src/pages/AccountPage.tsx
=> :recycle: Move logout to profile page

src/App.tsx, src/components/PrescriptionTr.tsx, src/components/Prescriptions.tsx, src/pages/AccountPage.tsx, src/pages/PatientCreatePage.tsx, src/pages/PatientsPage.tsx, src/pages/PrescriptionCreatePage.tsx, src/pages/ProfilePage.tsx
- The size was missing to make it possible to see the end 
- Added height to allow scrolling
- I've added  navigation to this fix when updating the profile
- I removed the background color blue in the titles
=> :wrench: add style on div

src/components/PrescriptionTr.tsx, src/components/Prescriptions.tsx, src/components/SearchBar.tsx, src/i18n.ts, src/pages/PatientsPage.tsx
- An enhancement is planned #185
for filter by patient in list prescription
- Fetch patient and switch to parent component and
patient is switched to props for each prescription
-Added search bar for patients and prescriptions
=> :sparkles: add search bar

src/App.tsx, src/components/LoginForm.tsx, src/components/NewResetPasswordForm.tsx, src/i18n.ts, src/pages/LoginPage.tsx, src/pages/NewResetPassword.tsx, src/pages/ResetPassword.tsx, src/services/api.ts, src/services/constants.ts
- Add endpoint for confirme the password reset
=> :sparkles: Add landing page to reset password fix #187

src/types/index.ts, src/utils/helpers.test.ts
We have taken the decision to cancel the renewal
because the notifications are based on the following dates
=> :fire: Remove at renew of app fix #111

src/components/AccountCard.tsx, src/pages/accounts/AccountPage.tsx
=> :recycle: Refactor account page

src/components/Error.tsx, src/components/Errors.tsx, src/components/forms/LoginForm.tsx, src/components/forms/PatientForm.tsx, src/components/forms/PrescriptionForm.tsx, src/components/forms/RegisterForm.tsx, src/context/error.tsx, src/i18n.ts, src/pages/accounts/ProfilePage.tsx
- Modify flash message system for error to make it generic
- We can use this message context to send error or success messages
=> :wrench: Modify alert error fix #112

src/App.css, src/App.tsx, src/components/Footer.tsx, src/components/Header.tsx, src/components/HeaderProfile.tsx, src/components/NavigationLink.tsx, src/components/NavigationLinks.tsx, src/components/PageHeader.tsx, src/components/Prescriptions.tsx, src/components/TitlePage.tsx, src/hook/profile.hook.ts, src/i18n.ts, src/pages/accounts/AccountPage.tsx, src/pages/patients/PatientDetail.tsx, src/utils/constants.ts
rename file for the navbar footer
Add a height for app
=> :wrench: Add navbar top screen

src/components/SelectPatient.tsx, src/components/forms/PrescriptionForm.tsx, src/types/index.ts
In the 'PrescriptionForm.tsx' file,
when the user selects a value in this field
which is not equal to 'addNewPatient',
the 'setNewCreatedPatientId(Number(value))' function is called.
=> :wrench: fix create prescription page

src/components/PatientLine.tsx, src/components/forms/PatientForm.tsx, src/components/forms/PrescriptionForm.tsx, src/components/modal/ModalAddPatient.tsx, src/i18n.ts, src/pages/patients/PatientDetail.tsx, src/types/index.ts
The Patient interface has been updated to replace address with street New fields birthday, health_card_number, and ss_provider_code have been added to the Patient type
Prescription:
- Removed the form groups related to caisseDeRattachement and carteVitale
=> :wrench: Refactor patient and prescription

package.json, src/App.tsx, src/services/oneSignal/OneSignalManager.tsx, yarn.lock
The SDK is correctly integrated, and OneSignal initialization is error-free
=> :sparkles: Add initialization of OneSignal

src/components/forms/PatientForm.tsx, src/components/forms/PrescriptionForm.tsx, src/components/modal/ModalAddPatient.tsx, src/i18n.ts, src/services/constants.ts, src/types/index.ts
- Create a patient with required fields only
=> :wrench: Updated modal in prescription

src/components/PatientLine.tsx, src/components/PrescriptionTr.tsx, src/components/Prescriptions.tsx, src/types/index.ts, src/utils/constants.ts, src/utils/helpers.test.ts, src/utils/helpers.ts
This commit add the color warning
=> :wrench: Add color badge

src/components/home/PatientCard.tsx, src/pages/HomePage.tsx
On the home page, you can now click on a patient in the "Expired" section, and it will take you directly to their patient record.
=> :sparkles: Make Expired Patients Clickable

src/components/prescriptions/precriptionProfile.tsx/PrescriptionField.tsx
Now we can open the link in a new tab
=> :bug: Fix link with anchor

src/components/flashMessages/FlashMessage.tsx, src/components/flashMessages/FlashMessages.tsx, src/components/forms/LoginForm.tsx, src/components/forms/validations/ValidationLogin.ts, src/context/flashmessage.tsx, src/i18n.ts, src/types/index.ts
The login form previously used custom state management and event handlers for form validation. This change replaces the custom approach with the use of React Hook Form, which provides a more robust and scalable solution for form handling and validation.
Key changes:
- Integrated the `useForm` hook from React Hook Form
- Moved the form validation logic to a separate `ValidationLogin` module using the `Resolver` pattern
- Updated the `LoginForm` component to use the `useForm` hook and the `resolver` function from `ValidationLogin`
- Removed the custom state management and event handlers for form fields
- Improved error messaging by leveraging the built-in error handling of React Hook Form
=> :sparkles: Replace custom validation

src/components/FormFieldError.tsx, src/components/forms/ProfileForm.tsx, src/components/forms/RegisterForm.tsx, src/components/forms/inputGroups/Input.tsx, src/components/forms/validations/ValidationProfile.ts, src/components/forms/validations/ValidationRegister.ts, src/i18n.ts
Add validation react hook form
=> :sparkles: Fix validation register form

src/components/forms/PrescriptionForm.tsx, src/utils/helpers.ts
This update introduces a more interactive and user-friendly file handling experience in the PrescriptionForm component, allowing users to preview their uploaded prescription files directly in the form.
=> :sparkles: Enhance with file preview functionality

src/services/oneSignal/OneSignalManager.tsx
- Implement event listener for OneSignal push subscription changes
- Ensure user is logged in and subscription ID is recorded in database
- Prevent actions when profile ID is invalid
- Set OneSignal as initialized after successful subscription change
=> :bug: Add push subscription change listener

src/components/Header.tsx, src/components/PageHeader.tsx, src/utils/constants.ts
- Moved page header logic to a separate function `getPageHeaderProps` in Header component.
- Simplified conditional rendering for back button and title in PageHeader.
- Added `showBackButton` prop to PageHeader for better control over back button visibility.
- Updated PAGE_CONFIG to include `showBackButton` property for relevant pages.
- Cleaned up unnecessary checks and improved overall code readability.
=> :bug: Refactor Header and PageHeader fix #309

src/components/Header.tsx, src/pages/HomePage.tsx
- Modified the redirection logic in the HomePage to navigate to the patient's prescription instead of the patient record.
=> :bug: Update redirection logic for "Expire Soon" fix#281

src/components/forms/ProfileForm.tsx, src/components/forms/inputGroups/Input.tsx, src/components/forms/inputGroups/InputFieldContainer.tsx, src/pages/setting/AccountPage.tsx
- Updated icons in `ProfileForm` to better reflect input fields (switched user icon for username and lock icon for password).
- Added `disabled` prop handling in `InputFieldContainer` to provide visual feedback (grayed out, non-clickable style).
- Enhanced `Input` component with `clsx` for conditional class handling and added `className` prop for custom styling.
- Adjusted initials generation in `AccountPage` to use `first_name` and `last_name` for better clarity and accuracy.
=> :sparkles: Refactor ProfileForm icons and improve input

src/services/api.ts
- Modified `login` function to accept `email` instead of `username` for authentication.
- Updated API endpoint to `API_V2` for token authentication.
- Adjusted request payload in `login` function to reflect the change from `username` to `email`.
=> Update login function to use email instead of username

package.json
This is useful confirm which version we're running. Use like so: `process.env.REACT_APP_VERSION`
=> :technologist: Add VERSION environment variable

src/components/forms/LoginForm.tsx, src/components/forms/ProfileForm.tsx, src/components/forms/RegisterForm.tsx, src/pages/authentifications/ResetPassword.tsx
This update solves the login problem when users enter their email address in uppercase.
=> :bug: Fix sanitization of email addresses fixes #348

src/App.tsx, src/context/subscription.tsx, src/hook/subscription.hook.ts, src/services/api.ts, src/types/index.ts
- Create subscription context to manage subscription state
- Add subscription provider wrapper in App.tsx
- Implement useSubscription hook for subscription data access
- Add getSubscriptionById API service
=> :sparkles: Add subscription context & hooks

src/App.tsx, src/components/subscriptions/LegalLinks.tsx, src/components/subscriptions/ManageSubscription.tsx, src/components/subscriptions/NextPaymentSubscribe.tsx, src/components/subscriptions/PlanSelection.tsx, src/components/subscriptions/PlanSelectionHeader.tsx, src/components/subscriptions/ProductStatusCard.tsx, src/components/subscriptions/StartPaymentSubscribe.tsx, src/components/subscriptions/UnsubscribeConfirmation.tsx, src/components/subscriptions/UnsubscribeSection.tsx, src/context/subscription.tsx, src/hook/subscription.hook.ts, src/hook/subscription.ts, src/i18n.ts, src/pages/setting/AccountPage.tsx, src/pages/subscription/Subscription.tsx, src/services/api.ts, src/types/index.ts, src/utils/constants.ts
- Add new Subscription page with plan selection and management
- Create components for subscription details, plan selection, and unsubscribe
- Update context and types to support subscription functionality
- Add subscription-related routes and navigation
- Implement API methods for creating and canceling subscriptions
=> :sparkles: Implement complete subscription management flow fixes #356

src/components/modal/ModalConfirmSend.tsx, src/components/navigationFooter/IconButtonAdd.tsx
- Implement subscription-based access control for IconButtonAdd
- Add modal to prompt users to subscribe when trying to access restricted features
- Modify IconButtonAdd to check subscription status before allowing action
- Create modal dialog for subscription upsell
=> :sparkles: Add access control to feature creation fixes #355

package-lock.json, package.json
- Regression of `serve` version (14.2.4 → 12.0.0) to avoid possible incompatibilities.
- Added `identity-obj-proxy` and Jest configurations (`transformIgnorePatterns` and `moduleNameMapper`) to improve unit testing.
=> :package: Updated `package.json` :

src/App.tsx, src/components/SearchBar.tsx, src/components/forms/PatientForm.tsx, src/components/forms/inputGroups/Button.tsx, src/components/forms/inputGroups/Input.tsx, src/components/forms/inputGroups/InputField.tsx, src/components/forms/inputGroups/InputFieldContainer.tsx, src/components/pageSections/detail/InfoRow.tsx, src/components/patients/PatientsPage/PatientLine.tsx, src/pages/patients/PatientCreatePage.tsx, src/pages/patients/PatientDetail.tsx, src/pages/patients/PatientEdit.tsx, src/pages/patients/PatientsPage.tsx
- to use Container component; enhance Input and SearchBar styles
=> :art: Refactor Patient creation and editing pages

src/components/forms/PrescriptionForm.tsx, src/components/modal/ModalAddPatient.tsx, src/components/prescriptions/PrescriptionLine.tsx, src/i18n.ts, src/pages/prescriptions/PrescriptionDetail.tsx, src/pages/prescriptions/PrescriptionEdit.tsx, src/pages/prescriptions/PrescriptionsPage.tsx
- new PrescriptionLine component and improves prescription display
=> :art: Adds prescription management

src/components/home/MainStats.tsx
- to use buttons for patient and prescription navigation
=> :sparkles: Refactor MainStats component fixes #393

src/components/home/PatientDaysRemaining.tsx, src/components/home/PrescriptionSoon.tsx, src/pages/HomePage.tsx
to display days remaining before prescriptions expire
=> :sparkles: PatientDaysRemaining component added

src/pages/patients/PatientDetail.tsx
to improve prescription display and remove unused code
=> :recycle: Refactor PatientDetail component to improve fixes #399

src/components/Header.tsx, src/utils/constants.ts
- Replace static back paths with browser history navigation
- Show back button on all non-home pages
- Remove backTo configuration from PAGE_CONFIG
- Simplify navigation logic in Header component
=> :recycle: improve back navigation using browser history

src/components/home/PatientDaysRemaining.tsx, src/components/home/PrescriptionSoon.tsx, src/hook/daysRemaining.ts
For prescriptions and filter valid patients
=> :recycle: Improve display of remaining days
