mynotif/mynotif-frontend

src/pages/PatientsPage.tsx, src/pages/PrescriptionsPage.tsx, src/services/api.ts
Both `/patients/` and `/prescriptions/` are now under authentication
and require a token.
=> :alien: API list now requires a token

src/components/Header.tsx, src/components/Logout.tsx, src/types/index.ts, src/utils/hooks.ts
Erases the token from the local storage if the backend returns a 401
with an "Invalid token" message.
Introduces a new `useLogout()` hook that's used in both fetch profile
invalid token error and explicit logout (button click).
=> :goal_net: Handle invalid token backend 401 error, fixes #57

README.md, package.json
Heroku no longer offers free plans.
Backend not yet migrated.
New URL:
https://mynotif.vercel.app/
=> :bricks: Migrated from Heroku to Vercel a while ago

.github/workflows/tests.yml, Dockerfile, README.md, package.json
Fixes the `ERR_OSSL_EVP_UNSUPPORTED` error.
=> :bug: Explicit node version 16 and update org references

src/components/Footer.tsx, src/components/FooterNav.tsx
This commit introduces the ability to handle external URLs in the FooterNav component, allowing for both internal navigation within the PWA and external redirections. A new prop `isExternal` has been added to differentiate between internal and external links. This enhancement fixes the issue where the admin link was incorrectly concatenated, leading to navigation errors.
=> :bug: Fix external links for admin redirection

src/i18n.ts
This allows your application to respond more flexibly to user language preferences. For example, a user with a browser configured for fr-CA (Canadian French) will be automatically redirected to the standard French translations.
=> :bug: Fix allows i18next to automatically recognize

package.json, public/OneSignalSDKWorker.js, src/App.tsx, src/index.tsx, src/services/api.ts, src/services/constants.ts, src/services/oneSignal/OneSignalManager.tsx, src/types/index.ts, yarn.lock
- Update the react-onesignal package from version 2.0.4 to 3.0.1
- Integrate state and context management in OneSignalManager
- Implement createSubscriptionIdOneSignal function to manage subscription IDs through the OneSignal API.
- Adjust App component structure for better context encapsulation.
- Add OneSignal type definitions
- Remove StrictMode from ReactDOM.render to simplify the rendering process.
=> :sparkles: Upgrade react-onesignal and refactor OneSignalManager component

src/utils/helpers.ts
This commit addresses an issue where the badge color remains green even when the prescription is set to expire within the next 7 days. The condition has been updated to ensure that the badge color accurately reflects the expiration status of the prescription.
=> :bug: Fix badge color display issue for expiring prescriptions

src/components/Header.tsx
The header component has been updated to correctly maintain the URL of the previous page. This ensures that the user can easily return to the page they were on before navigating to the current page.
Changes include:
- Using sessionStorage to store and retrieve the previous and current paths.
- Updating previousPath only when the location pathname changes.
- Ensuring the previousPath persists even when the component is unmounted and remounted.
=> :sparkles: Maintain previous page URL in header

src/components/HeaderProfile.tsx, src/components/module/LogoPng.tsx
- Replace logo component with LogoPng in HeaderProfile
- Increase logo size to 150px
- Improve flexibility of LogoPng component with props for size and font
- Customize style for better rendering and positioning
=> :lipstick: Customize Logo on Start Page

src/components/forms/PrescriptionForm.tsx
- Updated PrescriptionForm to generate a unique file name for uploaded prescription photos to avoid overflow issues.
=> :sparkles: Handle file name overflow

src/services/oneSignal/OneSignalManager.tsx
- Adjust OneSignal notify button offset
- Move bell to bottom right, above navigation bar
- Temporary solution to prevent overlap with profile button
- refs 298
=> :bug: Temporarily reposition notification bell

src/components/modal/ModalAddPatient.tsx
- Add bg-black and bg-opacity-50 classes to create a semi-transparent dark overlay
=> Add dark overlay to modal background fix #310

src/components/PrescriptionFilter.tsx, src/pages/prescriptions/PrescriptionsPage.tsx
- Added a new component 'PrescriptionFilter' to handle filtering prescriptions
- Updated the 'PrescriptionsPage' to use the new 'PrescriptionFilter' component
- Implemented logic to filter prescriptions based on expiring soon, in progress, and completed status
- Ensured that only one filter can be active at a time
=> :sparkles: Add pre-filter to search bar fix 279

src/components/prescriptions/PrescriptionCard.tsx, src/hook/daysRemaining.ts
- Add custom hook useDaysRemaining to calculate remaining days
- Display remaining days instead of end date when prescription is active
- Handle pluralization for "jour(s)" and "restant(s)"
=> :sparkles: Display days remaining until end date fix 283

.github/workflows/tests.yml, src/utils/helpers.test.ts
As we migrate dependencies, some errors popped up regarding our prescriptions instances not matching recent Prescription types updates.
This pull request isolate that specific change to prevent from having a too large pull request.
=> :white_check_mark: Fix helpers tests to honor types

package-lock.json, package.json
The warning was:
```
Creating an optimized production build...
One of your dependencies, babel-preset-react-app, is importing the
"@babel/plugin-proposal-private-property-in-object" package without
declaring it in its dependencies. This is currently working because
"@babel/plugin-proposal-private-property-in-object" is already in your
node_modules folder for unrelated reasons, but it may break at any time.
babel-preset-react-app is part of the create-react-app project, which
is not maintianed anymore. It is thus unlikely that this bug will
ever be fixed. Add "@babel/plugin-proposal-private-property-in-object" to
your devDependencies to work around this error. This will make this message
```
=> :rotating_light: Fix build warning

src/components/patients/PatientsPage/PatientLine.tsx, src/hook/patient.hook.ts, src/pages/HomePage.tsx, src/pages/patients/PatientsPage.tsx, src/services/api.ts
- Updated getPatients API to accept optional fields parameter for selective data fetching
- Modified PatientLine component to improve robustness and prevent potential undefined errors
- Updated usePatients hook to pass fields parameter to getPatients function
- Adjusted PatientsPage and HomePage to request only necessary patient fields
- Fixed minor syntax consistency issues across components
=> :zap: Make patient API fields optional

src/pages/prescriptions/PrescriptionsPage.tsx, src/types/index.ts, src/utils/helpers.test.ts
- Remove getPatient API call and patient data loading logic
- Add patient_firstname and patient_lastname fields to Prescription type
- Use patient name fields directly in PrescriptionsPage component
- Clean up unused imports and simplify code
=> :sparkles: simplify patient name handling in prescriptions page

src/components/forms/RegisterForm.tsx, src/components/forms/validations/ValidationRegister.ts, src/services/api.ts, src/types/index.ts
- Removed `username` field from RegisterForm component to simplify the registration process.
- Updated validation rules in `ValidationRegister.ts` to exclude username validation.
- Modified the `register` API method to accept only `password` and `email` parameters,
updating the API endpoint to `API_V2`.
- Adjusted the `RegisterFormType` interface to remove the `username` property.
=> :sparkles: Refactor RegisterForm to remove username field

src/components/Header.tsx, src/components/forms/ProfileForm.tsx, src/components/forms/validations/ValidationProfile.ts, src/pages/profile/ProfileDetail.tsx, src/pages/profile/ProfileEdit.tsx, src/pages/setting/AccountPage.tsx, src/types/index.ts
- Removed the `username` field from the `Profile`.
- Updated `Header`, `ProfileForm`, `ProfileDetail`, `ProfileEdit`, and `AccountPage` components to reflect this change.
- Adjusted display logic for initials and user information to utilize `first_name`, `last_name`, and `email` instead of `username`.
- Removed `ValidationProfile` validation rules related to `username`.
=> :sparkles: Remove username field from profile

src/pages/profile/ProfileEdit.tsx
There's no reason to check for the profile not to be empty before rendering the form. The profile can be filled asynchronously after the form is rendered this isn't a problem.
Also remove the unnecessary fragments.
=> :recycle: Simplify ProfileEdit
